apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.environment }}
data:
  etc-apache2-site-ssl.conf: |
{{ .Files.Get "config/etc-apache2-site-ssl.conf" | indent 4 }}

  etc-apache2.conf: |
{{ tpl ( .Files.Get "config/etc-apache2.conf" ) . | indent 4 }}
