apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-init-script
  namespace: {{ .Values.environment }}
data:
  init-script.sh: |
    #!/bin/bash

    # Install jq if not available
    JQ_URL=https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    JQ_BIN=/usr/local/bin/jq
    which jq 2>&1 > /dev/null || { curl -sfL $JQ_URL -o $JQ_BIN && chmod +x $JQ_BIN ; }

    # Generate settings.php from template
    cd /patched-files
    curl https://raw.githubusercontent.com/oda-hub/frontend-chart/master/config/drupal7_sites_default_settings.php.template -o settings.php
    sed -i "s@{{ "{{" }} mmoda_base_url {{ "}}" }}@${MMODA_BASE_URL}@" settings.php
    sed -i "s/{{ "{{" }}env.PASSWORD{{ "}}" }}/${PASSWORD}/" settings.php
    
    # avoid db deadlocks, see https://groups.drupal.org/node/415883
    cat <<EOF >> settings.php
    $databases['default']['default']['init_commands'] = array(
      'isolation' => "SET SESSION tx_isolation='READ-COMMITTED'"
    );
    EOF

    cp settings.php /var/www/mmoda/sites/default/settings.php
    cp /var/www/mmoda/sites/all/modules/mmoda/mmoda.nameresolver.inc .
    sed -i 's@$local_name_resolver_url = "https://resolver-prod.obsuks1.unige.ch/api/v1.1/byname/";@$local_name_resolver_url = "{{ .Values.resolver_endpoint }}";@'  mmoda.nameresolver.inc
    
    cp -rfv /frontend-default-files/* /var/www/mmoda/sites/default/files

    [ -d /instruments-dir ] && cp -rfv /var/www/mmoda/sites/all/modules/mmoda/instruments/* /instruments-dir

    # wait db
    function run-sql() {
        mysql -h mysql -u astrooda -p$PASSWORD astrooda < ${1:?}
    }
    while ! run-sql <(echo ";") ; do 
        sleep 10
    done

    # Drush reinstall all mmoda modules
    cd /var/www/mmoda 
    ALL_MMODA_MODULES=`~/.composer/vendor/bin/drush pm-list --type=module --format=json | jq -r '[ keys[] | select(startswith("mmoda_")) ] | join(",")'`
    ~/.composer/vendor/bin/drush dis -y mmoda 
    ~/.composer/vendor/bin/drush pm-uninstall -y $ALL_MMODA_MODULES
    ~/.composer/vendor/bin/drush pm-uninstall -y mmoda
    ~/.composer/vendor/bin/drush en -y mmoda 
    ~/.composer/vendor/bin/drush en -y $MMODA_MODULES
 

    chmod -R 777 /var/www/mmoda/sites/default/files

    #reset drupal admin
    ~/.composer/vendor/bin/drush user-create sitamin --password=$DRUPAL_PW
    ~/.composer/vendor/bin/drush user-add-role "administrator" sitamin
    ~/.composer/vendor/bin/drush upwd --password=$DRUPAL_PW sitamin

    run-sql <(echo "update variable set value='s:"$(echo -n $JWT_EXPIRATION | wc -c)":\"${JWT_EXPIRATION}\";' where name='jwt_link_expiration';")
    run-sql <(echo "update variable set value='s:"$(echo -n $JWT_KEY | wc -c)":\"${JWT_KEY}\";' where name='jwt_link_key';")
    run-sql <(echo "update variable set value='s:"$(echo -n $JWT_URL | wc -c)":\"${JWT_URL}\";' where name='jwt_link_key';")

    run-sql <(echo "use astrooda; update variable set value='s:30:"vendor/swiftmailer/swiftmailer";' where name='swiftmailer_path';")

    ~/.composer/vendor/bin/drush cc -y all 

    cp -rfv /var/www/mmoda/sites/all/modules/rules /patched-files/rules



    

