{{ if .Values.prepare_isdc_mount | default false }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-isilon-integral{{ .Values.pv_suffix }}
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 2Gi
  mountOptions:
  - vers=3
  - nolock
  nfs:
    path: {{ .Values.isdc.path_prefix }}
    server: {{ .Values.isdc.nfs_server }}
    readOnly: true    
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-isilon-integral
  # namespace: foo
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv-isilon-integral{{ .Values.pv_suffix }}
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi

{{ end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-files
spec:
  accessModes:
  - ReadWriteOnce
  #- ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: {{ .Values.storage_class }}
  #storageClassName: {{ .Values.storage_class_rwmany }}
  #volumeMode: Filesystem

{{ if .Values.extra_instr_dir.enabled | default false }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instruments-dir
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: {{ .Values.storage_class_rwmany }}
{{ end }}